# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: MMM DD (hh mmA [GMT])
    - name: Checking out repo
      uses: actions/checkout@v4

    - name: Set up Go v${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go get github.com/charmbracelet/bubbles
      run: go get github.com/charmbracelet/bubbletea
      run: go get github.com/charmbracelet/lipgloss
      run: go get github.com/charmbracelet/log
      run: go get github.com/charmbracelet/x/term
      run: go get github.com/evertras/bubble-table
      run: go get github.com/google/uuid
      run: go get go.etcd.io/bbolt
      run: go get google.golang.org/api

    - name: Build
      id: export
      run: go build -v -o youterm

    - name: Test
      run: go test -v 

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: YouTerm Linux - ${{ steps.current-time.outputs.formattedTime }} - Go v1.22
        path: youterm
        retention-days: 30
